name: Brakeman Scan
on:
  push:
    branches:
      - 'main'
      - 'master'
    paths:
      - '**.rb'
      - '**.html.erb'
      - '**.html.haml'
      - '**.html.slim'
      - 'Gemfile'
      - 'Gemfile.lock'
  pull_request:
    paths:
      - '**.rb'
      - '**.html.erb'
      - '**.html.haml'
      - '**.html.slim'
      - 'Gemfile'
      - 'Gemfile.lock'
  workflow_dispatch:
jobs:
  brakeman-scan:
    name: Brakeman Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Setup Brakeman
        env:
          BRAKEMAN_VERSION: '5.1.2'
        run: |
          gem install brakeman --version $BRAKEMAN_VERSION
      - name: Run Brakeman
        continue-on-error: true
        run: |
          brakeman --force -f sarif -o output.sarif.json .
      - name: Upload result
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: output.sarif.json
