name: Semgrep Scan
on:
  push:
    branches:
      - 'main'
      - 'master'
    paths:
      - '**.js'
      - '**.jsx'
  pull_request:
    paths:
      - '**.js'
      - '**.jsx'
  workflow_dispatch:
jobs:
  brakeman-scan:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Semgrep
        run: |
          python3 -m pip install semgrep
      - name: Run Semgrep
        run: |
          semgrep --sarif --config=auto -o output.sarif.json .
      - name: Upload result
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: output.sarif.json
